### ISSUE TITLE
Can I translate this article into Chinese and submit it to you?

### ISSUE THREAD

**Issue by ZimaBlue1996** [bravegnu/gnu-eprog#9]

**Comment by bravegnu** [comment]
Sure @liuhe-github Sorry for my delayed response.

**Comment by ZimaBlue1996** [comment]
Thank you very much, I will translate it when I have time.

**Comment by liuhe-github** [comment]
Now, I am translating the README.adoc.  I add README_cn.adoc file, but README.adoc say  "The tutorial is written in asciidoc.". ASCII is not include chinese language, so I use UTF-8 format.  It may affect automated builds.

**Comment by liuhe-github** [comment]
> Sure @liuhe-github Sorry for my delayed response.

Now, I am translating the README.adoc. I add README_cn.adoc file, but README.adoc say "The tutorial is written in asciidoc.". ASCII is not include chinese language, so I use UTF-8 format. It may affect automated builds.

**Comment by ZimaBlue1996** [comment]
Now, I am translating the README.adoc. I add README_cn.adoc file, but README.adoc say "The tutorial is written in asciidoc.". ASCII is not include chinese language, so I use UTF-8 format. It may affect automated builds. ( I don't know much about using the Issues feature yet, so I accidentally turned it off, hoping it didn't bother you. )

**Comment by ZimaBlue1996** [comment]
I know ! The asciidoc is not ascii.
